version: '3.9'

services:
  bot:
    container_name: bot
    build: .
    ports:
      - '8086:8086'
    depends_on:
      - ngrok
    environment:
      VK_API_VERSION: ${VK_API_VERSION}
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN}
      VK_CONFIRMATION_TOKEN: ${VK_CONFIRMATION_TOKEN}
      VK_GROUP_ID: ${VK_GROUP_ID}
    env_file:
      - .env
    networks:
      - app-network

  ngrok:
    container_name: ngrok-bot
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: 'http bot:8086'
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: app-network
